Add multiple wallet support
moonpay-hypermint/client-sdk pull request #7
Opened 2022-09-02 15:02 UTC by jono-hypermint

Apologies for the long messy PR. This work has been completed alongside the new storefront as and when changes were needed so has not been structured at all well 😢 

- Adds support for metamask, coinbase and wallet connect
- Replaces slow complicated rollup builds with simple webpack builds (eventually plan to add HMR for the example app). This change also enabled WalletConnect to be used as Rollup was not a fan of this
- Introduces new function to get the details of the currently connected wallet (docs PR to follow)

2022-09-08 12:08 UTC, ian-hypermint requested changes

2022-09-08 12:08 UTC, ian-hypermint commented on src/networks/EVMContract.ts
> -                    value: ethers.utils.parseEther(totalPrice.toString())
We sure we don't need this `parseEther` call with `totalPrice` for 721 buys on ethereum to work anymore? You still have it for 1155, wondering what the difference is

2022-09-08 12:08 UTC, ian-hypermint commented on src/networks/SolanaContract.ts
> +    public async getConnectedWallet(): Promise<any> {
I assume solana is just in a state that doesn't work now right? Just want to double check so I don't tell clients to use the solana sdk if they ask

2022-09-08 12:08 UTC, ian-hypermint commented on src/providers/WalletSelector.ts
> +const walletSelectorStylesheet = `
Do we want to put this css into its own file or is it easier to keep managing it in here? Not sure what the best practice is for frontend work like this

2022-09-08 12:08 UTC, ian-hypermint commented on src/providers/WalletSelector.ts
> +                    <div class="hm-wallet-logo"><img src="https://hypermint.com/client-sdk/resources/metamask.png" alt="MetaMask"/></div>
Verrrryyyy small note that can be fixed later but it looks like this metamask png has horrendously low resolution so might be worth updating the asset with a better quality version otherwise it could look bad on big screens

2022-09-08 12:21 UTC, jono-hypermint commented on global.d.ts
> +declare global {
This is a workaround to stop typescript moaning that the ethereum object doesn't exist on the window type. Its a bit ugly but its the only way 😞

2022-09-08 12:24 UTC, jono-hypermint commented on src/networks/SolanaContract.ts
> +    public async getConnectedWallet(): Promise<any> {
Yeah we really need to re-evaluate the state of our Solana work and get it all aligned

2022-09-08 15:27 UTC, jono-hypermint commented on src/providers/WalletSelector.ts
> +                    <div class="hm-wallet-logo"><img src="https://hypermint.com/client-sdk/resources/metamask.png" alt="MetaMask"/></div>
This is just a case of updating the image on the CDN we can do this at anytime

2022-09-09 09:32 UTC, ben-hypermint requested changes

2022-09-09 09:32 UTC, ben-hypermint commented on src/networks/EVMContract.ts
> +        if (!this.isPolygon() || !this.isMumbai()) {
Remove isPolygon as you can only get on Mumbai

2022-09-09 09:32 UTC, ben-hypermint commented on src/networks/EVMContract.ts
> +            let gasLimit = 100_000;
Reminder to increase/calculate

2022-09-09 09:32 UTC, ben-hypermint commented on src/networks/EVMContract.ts
> +                value: ethers.utils.parseEther(totalPrice.toString()),
Reminder to not use for Polygon as mentioned

2022-09-12 08:31 UTC, ben-hypermint approved these changes

2022-09-12 11:10 UTC, ian-hypermint approved these changes

2022-09-12 12:07 UTC, merged